server:
  Host: localhost
  Port: 8008

email:
  APIKey: <YOUR-SENDINBLUE-API-KEY>
  FromEmail: <YOUR-EMAIL>
  SignupVerificationTemplateName: email-verification-otp.gohtml

database:
  Host: localhost
  Port: 5432
  User: <YOUR-DB-USER>
  Password: <YOUR-DB-PASSWORD>
  Database: <YOUR-DB>
  SSLMode: disable
  PgDriver: postgres

redis:
  Addr: localhost:6379
  Username: <YOUR-REDIS-USER>
  Password: <YOUR-REDIS-PASSWORD>
  DB: 0
  MinIdleConns: 2
  MaxIdleConns: 5