version: '3'

env:
  POSTGRES: postgres://anordb16user:anordb16password@localhost:5432/anordb16?sslmode=disable
  TYPESENSE: http://typesense:8108
  MIGRATION_DIR: ./postgres/migrations

tasks:
  create-migration:
    desc: "creates a migration file"
    cmds:
      - GOOSE_DRIVER=postgres GOOSE_DBSTRING=$POSTGRES GOOSE_MIGRATION_DIR=$MIGRATION_DIR goose -s create {{.CLI_ARGS}} sql

  compose-up:
    cmds:
      - docker compose -f docker-compose.dev.yaml up -d

  compose-down:
    cmds:
      - docker compose -f docker-compose.dev.yaml down

  compose-logs:
    cmds:
      - docker compose -f docker-compose.dev.yaml logs

  compose-restart:
    cmds:
      - docker compose -f docker-compose.dev.yaml down
      - docker compose -f docker-compose.dev.yaml up -d --build --force-recreate --remove-orphans

  compose-clean-restart:
    cmds:
      - task: compose-down
      - docker volume rm anor_anor_data
      - sudo rm -rf ./_typesense-data
      - task: compose-up
      - sleep 5s
      - task: goose-up


  goose-up:
    cmds:
      - GOOSE_DRIVER=postgres GOOSE_DBSTRING=$POSTGRES goose -dir ./postgres/migrations up

  sqlc-gen: sqlc generate

  import-dataset:
    cmds:
      - go run ./cmd/ebay-data-importer/*.go -dataset-dir="./cmd/ebay-data-importer/dataset/" -database=$POSTGRES -typesense=$TYPESENSE {{ .CLI_ARGS}}