server:
  Host: <HOST>
  Port: 8008

email:
  APIKey: <API-KEY>
  Templates: ./brevo/templates/*.gohtml
  FromEmail: <EMAIL>
  SignupVerificationTemplateName: email_verification_otp.gohtml

database:
  Host: localhost
  Port: 5432
  User: anordb16user
  Password: anordb16password
  Database: anordb16
  SSLMode: disable
  PgDriver: postgres

redis:
  Host: localhost
  Port: 6379
  Username: <USERNAME>
  Password: <PASSWORD>
  DB: 0
  MinIdleConns: 2
  MaxIdleConns: 5

session:
  CookieName: __anor_session
  AuthLifetime: 1140h
  GuestLifetime: 720h

typesense:
  Host: localhost
  Port: 8108
  APIKey: xyz
  UseHTTPS: false

stripe:
  SecretKey: <SECRET-KEY>

google_oauth:
  ClientID: <GOOGLE-CLIENT-ID>
  ClientSecret: <GOOGLE-CLIENT-SECRET>
  RedirectURL: http://localhost:8008/auth/google/callback
  Scopes:
    - email
    - profile

logger:
  Level: debug
  Format: json
  AddSource: false
  TimeFormat: "Jan _2 15:04:05.000"